[phases.setup]
nixPkgs = ["gdal", "postgresql", "postgis"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python manage.py migrate --settings=config.settings.production && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"